{% set version = "0.3.2" %}

package:
  name: vine-phylo
  version: {{ version }}

source:
  url: https://github.com/CshlSiepelLab/vine/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5fe8f42a6ca84908d2d8f9416120526e4dc007a6ac0c2d7ead3d8d16f485c7ac

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('vine-phylo', max_pin='x') }}
  script:
    - if [[ -f "$PREFIX/lib/libopenblas.so.0" && ! -e "$PREFIX/lib/libopenblas.so" ]]; then ln -s "$PREFIX/lib/libopenblas.so.0" "$PREFIX/lib/libopenblas.so"; fi  # [linux]
    - cmake -S . -B build
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX=${PREFIX}
      -DPHAST_ROOT=${PREFIX}
    - cmake --build build --parallel ${CPU_COUNT}
    - cmake --install build

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - phast
    - pcre
    - blas
    - lapack
  run:
    - phast
    
test:
  commands:
    - vine --help

about:
  home: https://github.com/CshlSiepelLab/vine
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "VINE (phylogenetics): Variational Inference with Node Embeddings"
  description: |
    VINE is a tool for Bayesian variational phylogenetic inference.

extra:
  recipe-maintainers:
    - asiepel
